import { useCallback, useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { createOpeningBalance, createSettlement, createRefund, partnerBalanceEntries, partnerBalanceEntry, partnerBalances, partnerPage, reverseOpeningBalance, type PartnerBalance, type PartnerBalanceEntry, type PartnerRecord } from "@/api/business";
import { PageHeader } from "@/components/common/page-header";
import { DataTable } from "@/components/common/data-table";
import { DataTableCard } from "@/components/common/data-table-card";
import { Pagination } from "@/components/common/pagination";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import type { DataTableColumn } from "@/types";

const size=10;
function cents(value:string){if(!/^-?\d+(\.\d{1,2})?$/.test(value))return null;const [whole,fraction=""]=value.split(".");try{return (value.startsWith("-")?-1n:1n)*(BigInt(whole.replace("-",""))*100n+BigInt((fraction+"00").slice(0,2)))}catch{return null}}
function money(value:bigint){const magnitude=value<0n?-value:value;return `${value<0n?"-":""}${magnitude/100n}.${String(magnitude%100n).padStart(2,"0")}`}
export function PartnerBalancesPage({refundOnly=false}:{refundOnly?:boolean}){
 const navigate=useNavigate();
 const [refund,setRefund]=useState(refundOnly);
 const [balances,setBalances]=useState<PartnerBalance[]>([]),[balanceTotal,setBalanceTotal]=useState(0),[selectedBalance,setSelectedBalance]=useState<PartnerBalance|null>(null),[selectedEntry,setSelectedEntry]=useState<PartnerBalanceEntry|null>(null),[partners,setPartners]=useState<PartnerRecord[]>([]),[entries,setEntries]=useState<PartnerBalanceEntry[]>([]),[total,setTotal]=useState(0),[page,setPage]=useState(1),[balancePage,setBalancePage]=useState(1),[partnerId,setPartnerId]=useState(""),[direction,setDirection]=useState<"CUSTOMER"|"SUPPLIER">("CUSTOMER"),[amount,setAmount]=useState(""),[requestKey,setRequestKey]=useState(()=>crypto.randomUUID()),[date,setDate]=useState(new Date().toISOString().slice(0,10)),[description,setDescription]=useState(""),[method,setMethod]=useState("CASH"),[transactionNo,setTransactionNo]=useState(""),[remark,setRemark]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 const reload=useCallback(()=>{void partnerBalances({page:balancePage,pageSize:size,direction}).then(x=>{setBalances(x.records);setBalanceTotal(x.total)});void (partnerId?partnerBalances({page:1,pageSize:1,partnerId,direction}).then(x=>setSelectedBalance(x.records[0]??null)):Promise.resolve(setSelectedBalance(null)));void partnerPage({page:1,pageSize:500}).then(x=>setPartners(x.records));void partnerBalanceEntries({page,pageSize:size,partnerId:partnerId||0,direction}).then(x=>{setEntries(x.records);setTotal(x.total)});},[page,balancePage,partnerId,direction]);
 useEffect(()=>{reload()},[reload]);
 async function save(){setBusy(true);setMessage("");try{await createOpeningBalance({requestKey,partnerId:Number(partnerId),direction,amount,businessDate:date,description});setAmount("");setDescription("");setRequestKey(crypto.randomUUID());setMessage("期初金额已生效");reload()}catch(e){setMessage(e instanceof Error?e.message:"保存失败，请检查输入后重试")}finally{setBusy(false)}}
 async function saveSettlement(){if(!selectedBalance||!partnerId)return;const before=cents(selectedBalance.amount),value=cents(amount);if(before===null||value===null)return;const preview=`往来单位：${selectedBalance.partnerName}\n方向：${refund?(direction==="CUSTOMER"?"向客户退款":"收到供应商退款"):(direction==="CUSTOMER"?"客户收款":"供应商付款")}\n金额：${amount} 元\n余额变化：${selectedBalance.amount} → ${money(before+(refund?value:-value))} 元\n方式：${method}`;if(!window.confirm(preview))return;setBusy(true);setMessage("");try{await (refund?createRefund:createSettlement)({requestKey,partnerId:Number(partnerId),direction,amount,businessDate:date,paymentMethod:method,transactionNo,remark});setMessage(refund?"退款已生效":"收付款已生效");setAmount("");setTransactionNo("");setRemark("");setRequestKey(crypto.randomUUID());reload()}catch(e){setMessage(e instanceof Error?e.message:"保存失败，请检查输入后重试")}finally{setBusy(false)}}
 async function reverse(row:PartnerBalanceEntry){const reason=window.prompt("请填写冲销原因");if(!reason?.trim())return;setBusy(true);try{await reverseOpeningBalance(row.id,reason);setMessage("已追加冲销记录");reload()}catch(e){setMessage(e instanceof Error?e.message:"冲销失败")}finally{setBusy(false)}}
 const current=cents(selectedBalance?.amount??"0.00"),delta=cents(amount),next=current!==null&&delta!==null?money(current+delta):"—";
 const balanceColumns:DataTableColumn<PartnerBalance>[]=[{title:"往来单位",dataIndex:"partnerName"},{title:"方向",dataIndex:"direction",render:v=>v==="CUSTOMER"?"客户应收":"供应商应付"},{title:"当前余额",dataIndex:"amount",render:v=><span className="tabular-nums font-medium">{String(v)} 元</span>},{title:"状态",key:"status",render:(_,r)=>!r.hasRecords?"尚无记录":r.amount==="0.00"?"净结清":r.amount.startsWith("-")?"待退款":"欠款"},{title:"来源记录",dataIndex:"entryCount"}];
 const columns:DataTableColumn<PartnerBalanceEntry>[]=[{title:"单号 / 来源",key:"documentNo",render:(_,r)=><Button size="sm" variant="secondary" onClick={()=>void partnerBalanceEntry(r.id).then(setSelectedEntry)}>{r.documentNo}</Button>},{title:"业务日期",dataIndex:"businessDate"},{title:"类型 / 方式",key:"entryType",render:(_,r)=>({OPENING:"期初",RECEIPT:"客户收款",PAYMENT:"供应商付款",CUSTOMER_REFUND:"客户退款",SUPPLIER_REFUND:"供应商退款",SALE_RETURN:"销售退货",PURCHASE_RETURN:"采购退货",PURCHASE:"采购入库",SALE:"销售出库",REVERSAL:"冲销"}[r.entryType]??r.entryType)+(r.paymentMethod?` · ${r.paymentMethod}`:"")},{title:"说明",dataIndex:"description"},{title:"变动金额",dataIndex:"amount",render:v=><span className="tabular-nums">{String(v)}</span>},{title:"变动后余额",dataIndex:"balanceAfter",render:v=><span>{String(v)} {String(v).startsWith("-")?"待退款":v==="0.00"?"净结清":"欠款"}</span>},{title:"实际生效",dataIndex:"effectiveAt",render:v=>new Date(String(v)).toLocaleString()},{title:"操作",key:"action",render:(_,r)=>(r.entryType==="OPENING"||r.entryType==="RECEIPT"||r.entryType==="PAYMENT"||r.entryType==="CUSTOMER_REFUND"||r.entryType==="SUPPLIER_REFUND")&&!r.reversedById?<Button size="sm" variant="secondary" onClick={()=>void reverse(r)}>冲销</Button>:r.reversesId?"冲销记录":r.reversedById?"已冲销":"—"}];
 return <><PageHeader title={refundOnly?"客户退款 / 供应商退款":"往来余额与期初录入"} description="客户应收和供应商应付分别记账。期初保存即生效；录错通过填写原因冲销后重录。"/>
 <section className="mb-4 rounded-admin border border-border bg-surface p-4"><h2 className="mb-3 font-medium">录入期初应收 / 应付</h2><div className="grid gap-3 md:grid-cols-3"><Select aria-label="往来方向" value={direction} onChange={e=>{setDirection(e.target.value as typeof direction);setPartnerId("")}}><option value="CUSTOMER">客户应收</option><option value="SUPPLIER">供应商应付</option></Select><Select aria-label="往来单位" value={partnerId} onChange={e=>setPartnerId(e.target.value)}><option value="">选择往来单位</option>{partners.filter(p=>direction==="CUSTOMER"?p.isCustomer:p.isSupplier).map(p=><option key={p.id} value={p.id}>{p.name}（{p.code}）</option>)}</Select><Input aria-label="期初金额" placeholder="金额，例如 1200.00" value={amount} onChange={e=>setAmount(e.target.value)}/><Input aria-label="业务日期" type="date" value={date} onChange={e=>setDate(e.target.value)}/><Textarea aria-label="说明" placeholder="必填说明" value={description} onChange={e=>setDescription(e.target.value)}/><div className="flex items-center text-sm">确认后余额：{next} 元 {current!==null&&delta!==null&&current+delta>0n?"（欠款增加）":""}</div></div><div className="mt-3 flex items-center gap-3"><Button disabled={busy||!partnerId||!amount||!description.trim()} onClick={()=>void save()}>保存并生效</Button><span role="status" className="text-sm text-text-secondary">{message}</span></div></section>
 <section className="mb-4 rounded-admin border border-border bg-surface p-4"><h2 className="mb-3 font-medium">{refund?"按待退款向客户退款 / 收到供应商退款":"按总欠款收款 / 付款"}</h2><Select aria-label="资金记录类型" value={refund?"REFUND":"SETTLEMENT"} onChange={e=>{setRefund(e.target.value==="REFUND");setRequestKey(crypto.randomUUID())}}><option value="SETTLEMENT">客户收款 / 供应商付款</option><option value="REFUND">客户退款 / 供应商退款</option></Select><p className="mb-3 text-sm text-text-secondary">不分配到单据。当前方向余额为 {selectedBalance?.amount??"0.00"} 元；{refund?"正金额不能超过当前待退款。":"只可结算正欠款。"}</p><div className="grid gap-3 md:grid-cols-3"><Select aria-label="结算方向" value={direction} onChange={e=>{setDirection(e.target.value as typeof direction);setPartnerId("")}}><option value="CUSTOMER">客户收款</option><option value="SUPPLIER">供应商付款</option></Select><Select aria-label="结算往来单位" value={partnerId} onChange={e=>setPartnerId(e.target.value)}><option value="">选择往来单位</option>{partners.map(p=><option key={p.id} value={p.id}>{p.name}（{p.code}）</option>)}</Select><Input aria-label="收付款金额" placeholder="结算金额" value={amount} onChange={e=>setAmount(e.target.value)}/><Input aria-label="结算业务日期" type="date" value={date} onChange={e=>setDate(e.target.value)}/><Select aria-label="收付款方式" value={method} onChange={e=>setMethod(e.target.value)}><option value="CASH">现金</option><option value="WECHAT">微信</option><option value="ALIPAY">支付宝</option><option value="BANK_TRANSFER">银行转账</option><option value="OTHER">其他</option></Select><Input aria-label="交易流水号" placeholder="交易流水号（选填）" value={transactionNo} onChange={e=>setTransactionNo(e.target.value)}/><Textarea aria-label="收付款备注" placeholder="备注（选填）" value={remark} onChange={e=>setRemark(e.target.value)}/><div className="flex items-center text-sm">确认后余额：{current!==null&&delta!==null&&(refund?current<0n&&delta<=-current:current>=delta)?money(current+(refund?delta:-delta)):"—"} 元</div></div><div className="mt-3 flex items-center gap-3"><Button disabled={busy||!partnerId||!amount||current===null||delta===null||delta<=0n||(refund?current>=0n||delta>-current:current<=0n||delta>current)} onClick={()=>void saveSettlement()}>确认并保存</Button><span role="status" className="text-sm text-text-secondary">{message}</span></div></section>
 <DataTableCard toolbar={<div className="p-3 text-sm">往来余额 · {direction==="CUSTOMER"?"客户应收":"供应商应付"}</div>} pagination={<Pagination page={balancePage} pageSize={size} total={balanceTotal} onPageChange={setBalancePage}/>}><DataTable columns={balanceColumns} dataSource={balances} rowKey={r=>`${r.partnerId}-${r.direction}`}/></DataTableCard>
 <div className="my-3 flex flex-wrap gap-3"><Select aria-label="明细往来单位" value={partnerId} onChange={e=>{setPage(1);setPartnerId(e.target.value)}}><option value="">全部往来单位</option>{partners.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</Select><Select aria-label="明细方向" value={direction} onChange={e=>{setBalancePage(1);setPage(1);setDirection(e.target.value as typeof direction)}}><option value="CUSTOMER">客户应收</option><option value="SUPPLIER">供应商应付</option></Select></div>
 {selectedEntry&&<section className="my-3 rounded-admin border border-border bg-surface p-4 text-sm"><div className="mb-2 flex items-center justify-between"><strong>往来记录详情</strong><Button size="sm" variant="secondary" onClick={()=>setSelectedEntry(null)}>关闭</Button></div><div>{selectedEntry.documentNo} · {({OPENING:"期初录入",RECEIPT:"客户收款",PAYMENT:"供应商付款",CUSTOMER_REFUND:"客户退款",SUPPLIER_REFUND:"供应商退款",SALE_RETURN:"销售退货",PURCHASE_RETURN:"采购退货",REVERSAL:"冲销",SALE:"销售出库",PURCHASE:"采购入库"}[selectedEntry.entryType]??selectedEntry.entryType)} · {selectedEntry.amount} 元 · 业务日期 {selectedEntry.businessDate} · 实际生效 {new Date(selectedEntry.effectiveAt).toLocaleString()} · 操作人 ID {selectedEntry.operatorId}{selectedEntry.paymentMethod?` · ${selectedEntry.paymentMethod}`:""}{selectedEntry.transactionNo?` · 流水号 ${selectedEntry.transactionNo}`:""} · {selectedEntry.description}{selectedEntry.reversesId?` · 冲销来源 ${selectedEntry.reversesId}`:""}{selectedEntry.reversedById?` · 已由记录 ${selectedEntry.reversedById} 冲销`:""}</div>{selectedEntry.saleId&&<Button size="sm" className="mt-2" variant="secondary" onClick={()=>navigate(`/business/sales?saleId=${selectedEntry.saleId}`)}>打开销售单</Button>}</section>}
 <DataTableCard toolbar={<div className="p-3 text-sm">期初及冲销来源明细</div>} pagination={<Pagination page={page} pageSize={size} total={total} onPageChange={setPage}/>}><DataTable columns={columns} dataSource={entries} rowKey="id"/></DataTableCard></>;
}
