import { useCallback, useEffect, useState } from "react";
import { useNavigate, useSearchParams } from "react-router-dom";
import { partnerBalanceEntries, partnerBalanceEntry, partnerBalances, partnerPage, type PartnerBalance, type PartnerBalanceEntry, type PartnerRecord } from "@/api/business";
import { PageHeader } from "@/components/common/page-header";
import { SearchFilterBar } from "@/components/common/search-filter-bar";
import { DataTable } from "@/components/common/data-table";
import { DataTableCard } from "@/components/common/data-table-card";
import { Pagination } from "@/components/common/pagination";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import { entryTypeLabel, ledgerSource, localPeriod } from "@/lib/partner-ledger";
import type { DataTableColumn } from "@/types";
const size=20;
export function PartnerLedgerPage(){
 const navigate=useNavigate(),[params]=useSearchParams();
 const [partners,setPartners]=useState<PartnerRecord[]>([]),[balances,setBalances]=useState<PartnerBalance[]>([]),[records,setRecords]=useState<PartnerBalanceEntry[]>([]),[detail,setDetail]=useState<PartnerBalanceEntry|null>(null);
 const [partnerId,setPartnerId]=useState(params.get("partnerId")??""),[direction,setDirection]=useState(params.get("direction")==="SUPPLIER"?"SUPPLIER":"CUSTOMER"),[from,setFrom]=useState(""),[to,setTo]=useState(""),[page,setPage]=useState(1),[balancePage,setBalancePage]=useState(1),[total,setTotal]=useState(0),[balanceTotal,setBalanceTotal]=useState(0),[error,setError]=useState(""),[loading,setLoading]=useState(false),[version,setVersion]=useState(0);
 const [query,setQuery]=useState<Record<string,string|number>>({partnerId,direction});
 useEffect(()=>{void partnerPage({page:1,pageSize:500}).then(x=>setPartners(x.records)).catch(e=>setError(String(e)))},[]);
 useEffect(()=>{const id=Number(params.get("entryId"));if(id>0)void partnerBalanceEntry(id).then(setDetail).catch(e=>setError(e instanceof Error?e.message:"加载详情失败"))},[params]);
 const load=useCallback(()=>{let active=true;setLoading(true);setError("");void Promise.all([partnerBalanceEntries({...query,page,pageSize:size}),partnerBalances({partnerId:query.partnerId??0,direction:query.direction??"",page:balancePage,pageSize:size})]).then(([entries,amounts])=>{if(active){setRecords(entries.records);setTotal(entries.total);setBalances(amounts.records);setBalanceTotal(amounts.total)}}).catch(e=>{if(active)setError(e instanceof Error?e.message:"读取往来账失败")}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[query,page,balancePage,version]);
 useEffect(load,[load]);
 function search(){try{const range=from||to?localPeriod(from,to):{};setQuery({partnerId,direction,...range});setPage(1);setBalancePage(1)}catch(e){setError(e instanceof Error?e.message:"期间无效")}}
 function print(){try{const range=localPeriod(from,to);if(!partnerId)throw new Error("打印前请选择往来单位");navigate(`/business/partner-statements?${new URLSearchParams({partnerId,direction,...range})}`)}catch(e){setError(e instanceof Error?e.message:"打印条件无效")}}
 const balanceColumns:DataTableColumn<PartnerBalance>[]=[{title:"往来单位",dataIndex:"partnerName"},{title:"方向",dataIndex:"direction",render:v=>v==="CUSTOMER"?"客户":"供应商"},{title:"当前余额（元）",dataIndex:"amount"},{title:"状态",key:"status",render:(_,r)=>r.amount.startsWith("-")?"待退款":r.amount==="0.00"?"净零":"欠款"},{title:"操作",key:"action",render:(_,r)=><Button size="sm" variant="secondary" onClick={()=>{setPartnerId(String(r.partnerId));setDirection(r.direction);setQuery({partnerId:r.partnerId,direction:r.direction});setPage(1);setBalancePage(1)}}>查看明细</Button>}];
 const columns:DataTableColumn<PartnerBalanceEntry>[]=[{title:"往来单位",dataIndex:"partnerName"},{title:"类型 / 来源号",key:"source",render:(_,r)=><><span className="block text-xs text-text-secondary">{entryTypeLabel[r.entryType]??r.entryType}</span><Button size="sm" variant="secondary" onClick={()=>void partnerBalanceEntry(r.id).then(setDetail).catch(e=>setError(String(e)))}>{r.documentNo}</Button></>},{title:"业务日期",dataIndex:"businessDate"},{title:"实际生效",dataIndex:"effectiveAt",render:v=>new Date(String(v)).toLocaleString()},{title:"实际操作人",key:"actor",render:(_,r)=>`${r.operatorName??""}（${r.operatorId}）`},{title:"变动（元）",dataIndex:"amount"},{title:"前余额",dataIndex:"balanceBefore"},{title:"后余额",dataIndex:"balanceAfter"},{title:"来源",key:"action",render:(_,r)=><Button size="sm" variant="secondary" onClick={()=>navigate(ledgerSource(r))}>打开来源</Button>}];
 return <><PageHeader title="往来余额 / 明细账" description="客户与供应商分别记账。期间按实际生效时间筛选，业务日期同时保留；负余额为待退款。" actions={<Button onClick={print}>期间对账 / A4打印</Button>}/><SearchFilterBar actions={<><Button onClick={search}>查询</Button><Button variant="secondary" onClick={()=>setVersion(v=>v+1)}>刷新</Button></>}><Select aria-label="往来单位" value={partnerId} onChange={e=>setPartnerId(e.target.value)}><option value="">全部往来单位（含停用历史）</option>{partners.map(p=><option value={p.id} key={p.id}>{p.name}（{p.code}）</option>)}</Select><Select aria-label="往来方向" value={direction} onChange={e=>setDirection(e.target.value)}><option value="CUSTOMER">客户方向</option><option value="SUPPLIER">供应商方向</option></Select><label className="text-sm">生效开始日<Input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label className="text-sm">生效结束日（含当日）<Input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label></SearchFilterBar>
 <DataTableCard className="mb-4" toolbar={<div className="p-3 text-sm">当前余额（不随历史期间改变）</div>} pagination={<Pagination page={balancePage} pageSize={size} total={balanceTotal} onPageChange={setBalancePage}/>}><DataTable columns={balanceColumns} dataSource={balances} rowKey={r=>`${r.partnerId}-${r.direction}`} loading={loading} error={error}/></DataTableCard>
 {detail&&<section className="mb-4 rounded-admin border border-border bg-surface p-4 text-sm"><div className="flex items-center justify-between"><strong>往来记录详情 · {detail.documentNo}</strong><Button variant="secondary" size="sm" onClick={()=>setDetail(null)}>关闭</Button></div><p>{detail.partnerName} · {entryTypeLabel[detail.entryType]} · 业务日期 {detail.businessDate} · 生效 {new Date(detail.effectiveAt).toLocaleString()} · 操作人 {detail.operatorName}（{detail.operatorId}）</p><p>变动 {detail.amount} 元 · 余额 {detail.balanceBefore} → {detail.balanceAfter} 元</p><p>{detail.description} {detail.paymentMethod&&`· 方式 ${detail.paymentMethod}`} {detail.transactionNo&&`· 流水号 ${detail.transactionNo}`}</p><p>{detail.reversedDocumentNo&&`原始来源 ${detail.reversedDocumentNo}`} {detail.reversedById&&`已由往来记录 ${detail.reversedById} 冲销`}</p><Button variant="secondary" size="sm" onClick={()=>navigate(ledgerSource(detail))}>打开来源业务</Button></section>}
 <DataTableCard toolbar={<div className="p-3 text-sm">全部已生效来源 · 生效时间 / ID 升序</div>} pagination={<Pagination page={page} pageSize={size} total={total} onPageChange={setPage}/>}><DataTable columns={columns} dataSource={records} rowKey="id" loading={loading} error={error}/></DataTableCard></>;
}
