import { BusinessReturnLink } from "@/components/business/business-return-link";
import { DirectDeliveryTrace } from "@/components/business/direct-delivery-trace";
import { useCallback, useEffect, useState } from "react";
import { useNavigate, useSearchParams } from "react-router-dom";
import { cancelPurchaseReturn, createPurchaseReturn, getPurchaseReturn, getPurchaseReturnSource, postPurchaseReturn, purchaseReturnPage, updatePurchaseReturn, type PurchaseReturn, type PurchaseReturnSource } from "@/api/business";
import { DataTable } from "@/components/common/data-table";
import { DataTableCard } from "@/components/common/data-table-card";
import { DetailDialog } from "@/components/common/detail-dialog";
import { Field } from "@/components/common/field";
import { FormDialog } from "@/components/common/form-dialog";
import { PageHeader } from "@/components/common/page-header";
import { Pagination } from "@/components/common/pagination";
import { SearchFilterBar } from "@/components/common/search-filter-bar";
import { TableToolbar } from "@/components/common/table-toolbar";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { useBusinessLeaveGuard } from "@/hooks/use-business-leave-guard";
import { BusinessLeaveConfirm } from "@/components/business/business-leave-confirm";
import type { DataTableColumn } from "@/types";

type Line = {purchaseItemId:number;quantity:string;remark?:string};
const today=()=>{const d=new Date();return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10)};
export function PurchaseReturnsPage(){
 const navigate=useNavigate();const [params]=useSearchParams();const [page,setPage]=useState(1);const [rows,setRows]=useState<PurchaseReturn[]>([]);const [total,setTotal]=useState(0);const [filters,setFilters]=useState({documentNo:"",purchaseId:"",partnerId:"",status:"",businessFrom:"",businessTo:""});const [query,setQuery]=useState(filters);const [loading,setLoading]=useState(false);const [error,setError]=useState("");const [reload,setReload]=useState(0);
 const [source,setSource]=useState<PurchaseReturnSource|null>(null);const [editing,setEditing]=useState<PurchaseReturn|null>(null);const [open,setOpen]=useState(false);const [date,setDate]=useState(today());const [remark,setRemark]=useState("");const [lines,setLines]=useState<Line[]>([]);const [initialDraft,setInitialDraft]=useState<{date:string;remark:string;lines:Line[]}>({date:today(),remark:"",lines:[]});const [saving,setSaving]=useState(false);const [detail,setDetail]=useState<PurchaseReturn|null>(null);const [cancelTarget,setCancelTarget]=useState<PurchaseReturn|null>(null);const [reason,setReason]=useState("");
 const leaveGuard=useBusinessLeaveGuard({dirty:open&&JSON.stringify({date,remark,lines})!==JSON.stringify(initialDraft),busy:open&&saving});
 const load=useCallback(()=>{setLoading(true);void purchaseReturnPage({page,pageSize:10,...query}).then(x=>{setRows(x.records);setTotal(x.total);setError("")}).catch(e=>setError(e instanceof Error?e.message:"采购退货加载失败")).finally(()=>setLoading(false))},[page,query]);useEffect(()=>load(),[load,reload]);
 async function startCreate(purchaseId:number){try{const s=await getPurchaseReturnSource(purchaseId);const nextDate=today();const nextLines=s.items.map(i=>({purchaseItemId:i.purchaseItemId,quantity:"0"}));setSource(s);setEditing(null);setDate(nextDate);setRemark("");setLines(nextLines);setInitialDraft({date:nextDate,remark:"",lines:nextLines});setOpen(true);setError("")}catch(e){setError(e instanceof Error?e.message:"读取原采购单失败")}}
 async function startEdit(row:PurchaseReturn){try{const d=await getPurchaseReturn(row.id);const s=await getPurchaseReturnSource(d.purchaseId);const nextLines=s.items.map(item=>{const saved=d.items.find(i=>i.purchaseItemId===item.purchaseItemId);return {purchaseItemId:item.purchaseItemId,quantity:saved?.quantity??"0",remark:saved?.remark??undefined}});const nextDraft={date:d.businessDate,remark:d.remark??"",lines:nextLines};setSource(s);setEditing(d);setDate(nextDraft.date);setRemark(nextDraft.remark);setLines(nextLines);setInitialDraft(nextDraft);setOpen(true)}catch(e){setError(e instanceof Error?e.message:"读取草稿失败")}}
 useEffect(()=>{const id=Number(params.get("purchaseId"));if(id>0)void startCreate(id)},[params]);
 useEffect(()=>{const id=Number((params.get("purchaseReturnId")??params.get("returnId")));if(id>0)void getPurchaseReturn(id).then(setDetail).catch(e=>setError(e instanceof Error?e.message:"读取采购退货来源单失败"))},[params]);
 async function save(){if(!source)return;setSaving(true);try{const input={purchaseId:source.purchaseId,businessDate:date,remark:remark.trim()||undefined,items:lines.filter(x=>Number(x.quantity)>0).map(({purchaseItemId,quantity,remark:r})=>({purchaseItemId,quantity,remark:r}))};if(!input.items.length)throw new Error("请至少填写一行退货数量");if(editing)await updatePurchaseReturn(editing.id,{...input,version:editing.version});else await createPurchaseReturn(input);setOpen(false);setReload(x=>x+1)}catch(e){setError(e instanceof Error?e.message:"保存失败，表单内容已保留")}finally{setSaving(false)}}
 async function cancel(){if(!cancelTarget)return;setSaving(true);try{await cancelPurchaseReturn(cancelTarget.id,{version:cancelTarget.version,reason});setCancelTarget(null);setReload(x=>x+1)}catch(e){setError(e instanceof Error?e.message:"取消失败")}finally{setSaving(false)}}
 async function post(row:PurchaseReturn){setSaving(true);try{await postPurchaseReturn(row.id,{version:row.version});setReload(x=>x+1);setError("")}catch(e){setError(e instanceof Error?e.message:"过账失败，请刷新后重试")}finally{setSaving(false)}}
 const columns:DataTableColumn<PurchaseReturn>[]=[{title:"退货单号",dataIndex:"documentNo"},{title:"原采购单",dataIndex:"purchaseNo"},{title:"供应商",dataIndex:"partnerName"},{title:"业务日期",dataIndex:"businessDate"},{title:"单据金额",dataIndex:"totalAmount",align:"right",render:v=>`¥${v}`},{title:"状态",dataIndex:"status",render:v=>({DRAFT:"草稿",POSTED:"已过账",CANCELLED:"已取消"}[String(v)]??String(v))},{title:"操作",key:"actions",render:(_,r)=><div className="flex gap-2"><Button size="sm" variant="secondary" onClick={()=>void getPurchaseReturn(r.id).then(setDetail).catch(e=>setError(e.message))}>查看</Button>{r.status==="DRAFT"&&<><Button size="sm" variant="secondary" onClick={()=>void startEdit(r)}>编辑</Button><Button size="sm" variant="secondary" onClick={()=>void post(r)}>过账</Button><Button size="sm" variant="secondary" onClick={()=>{setCancelTarget(r);setReason("")}}>取消</Button></>}{r.status==="POSTED"&&<Button size="sm" variant="secondary" onClick={()=>{setCancelTarget(r);setReason("")}}>冲销取消</Button>}</div>}];
 return <div className="space-y-space-4"><PageHeader title="采购退货" description="退货过账会整单扣减库存与供应商欠款。取消已过账退货会按原金额、原数量冲回；同一原明细须按退货过账逆序取消。" actions={<Button onClick={()=>{const id=Number(params.get("purchaseId"));if(id>0)void startCreate(id);else setError("请从已过账采购单点击“办理退货”。")}}>新建退货草稿</Button>}/><SearchFilterBar actions={<><Button onClick={()=>{setPage(1);setQuery({...filters})}}>查询</Button><Button variant="secondary" onClick={()=>{const empty={documentNo:"",purchaseId:"",partnerId:"",status:"",businessFrom:"",businessTo:""};setFilters(empty);setQuery(empty);setPage(1)}}>重置</Button></>}>
 <Field label="退货单号"><Input value={filters.documentNo} onChange={e=>setFilters({...filters,documentNo:e.target.value})} placeholder="输入单号"/></Field>
 <Field label="原采购单ID"><Input inputMode="numeric" value={filters.purchaseId} onChange={e=>setFilters({...filters,purchaseId:e.target.value})}/></Field>
 <Field label="供应商ID"><Input inputMode="numeric" value={filters.partnerId} onChange={e=>setFilters({...filters,partnerId:e.target.value})}/></Field>
 <Field label="状态"><Select value={filters.status} onChange={e=>setFilters({...filters,status:e.target.value})}><option value="">全部状态</option><option value="DRAFT">草稿</option><option value="POSTED">已过账</option><option value="CANCELLED">已取消</option></Select></Field>
 <Field label="业务日期起"><Input type="date" value={filters.businessFrom} onChange={e=>setFilters({...filters,businessFrom:e.target.value})}/></Field><Field label="业务日期止"><Input type="date" value={filters.businessTo} onChange={e=>setFilters({...filters,businessTo:e.target.value})}/></Field>
 </SearchFilterBar>{error&&<p role="alert" className="text-sm text-error">{error}</p>}<DataTableCard toolbar={<TableToolbar title="采购退货单" description="按来源采购单查看单据；草稿额度仅作预览，过账时会重新校验。"/>} pagination={<Pagination page={page} pageSize={10} total={total} disabled={loading} onPageChange={setPage}/>}><DataTable columns={columns} dataSource={rows} rowKey="id" loading={loading} minWidth={900} empty="暂无采购退货单。"/></DataTableCard>
 <FormDialog open={open} title={editing?`编辑采购退货草稿 · ${editing.documentNo}`:"新建采购退货草稿"} description={source?`原单 ${source.purchaseNo} · ${source.partnerName} · 编辑版本 ${editing?.version??1}`:undefined} loading={saving} onCancel={()=>leaveGuard.requestClose(()=>setOpen(false))} trapFocus={!leaveGuard.open} closeOnEscape={!leaveGuard.open} closeOnOverlayClick={!leaveGuard.open} onSubmit={save}>{error&&<p role="alert" className="mb-3 text-sm text-error">{error}</p>}<DirectDeliveryTrace trace={source?.directTrace}/><div className="grid gap-space-3 md:grid-cols-2"><Field label="业务日期" required><Input type="date" value={date} onChange={e=>setDate(e.target.value)}/></Field><Field label="备注"><Input value={remark} onChange={e=>setRemark(e.target.value)} maxLength={500}/></Field></div><div className="mt-space-4 space-y-3">{source?.items.map(item=>{const line=lines.find(x=>x.purchaseItemId===item.purchaseItemId);const amount=previewAmount(item.returnedQuantity,line?.quantity??"0",item.unitPrice,item.priorReturnAmount);return <div key={item.purchaseItemId} className="rounded-control border border-border p-space-3"><p className="font-medium">{item.productCode} · {item.productName} {item.productModel||""} {item.productSpecification||""}</p><p className="text-sm text-text-tertiary">原数量 {item.originalQuantity} {item.unit} · 已过账退货 {item.returnedQuantity} · 剩余额度 {item.remainingQuantity} · 原单价 ¥{item.unitPrice} · 此前退货金额 ¥{item.priorReturnAmount}</p><div className="mt-2 grid gap-2 md:grid-cols-2"><Field label="本次退货数量"><Input inputMode="decimal" value={line?.quantity??"0"} onChange={e=>setLines(v=>v.map(x=>x.purchaseItemId===item.purchaseItemId?{...x,quantity:e.target.value}:x))}/></Field><p className="self-end pb-2 text-sm">累计取整差额预览：{amount===null?"—":`¥${amount}`}</p></div></div>})}</div><p className="mt-3 text-xs text-text-tertiary">停用商品和供应商的历史退货仍可办理。草稿不会预留退货数量；所有额度在过账时复核。</p></FormDialog><BusinessLeaveConfirm guard={leaveGuard} title={editing?"放弃采购退货修改？":"放弃新建采购退货？"} stayText="继续编辑" leaveText="放弃并关闭"/>
 <DetailDialog footer={<BusinessReturnLink />} open={detail!==null} title={detail?`采购退货 · ${detail.documentNo}`:"采购退货详情"} description={detail?`原单 ${detail.purchaseNo} · ${detail.partnerName} · ${detail.status}`:undefined} onCancel={()=>setDetail(null)}>{detail&&<><DirectDeliveryTrace trace={detail.directTrace}/><DataTable columns={[{title:"原采购明细ID",dataIndex:"purchaseItemId"},{title:"商品快照",key:"product",render:(_,i)=>`${i.productCode} ${i.productName}`},{title:"原数量/累计退货/剩余",key:"quota",render:(_,i)=>`${i.originalQuantity} / ${i.returnedQuantity} / ${i.remainingQuantity}`},{title:"本次数量",dataIndex:"quantity"},{title:"原价",dataIndex:"unitPrice"},{title:"退货金额",dataIndex:"amount"}]} dataSource={detail.items} rowKey="id" minWidth={760}/><p className="mt-3 text-right">退货金额：¥{detail.totalAmount}</p><p className="mt-2 text-sm text-text-tertiary">创建人：{detail.createdByName} · 创建时间：{new Date(detail.createTime).toLocaleString()}{detail.postedByName?` · 过账人：${detail.postedByName}${detail.postedAt?` · ${new Date(detail.postedAt).toLocaleString()}`:""}`:""}{detail.cancelledByName?` · 取消人：${detail.cancelledByName}${detail.cancelledAt?` · ${new Date(detail.cancelledAt).toLocaleString()}`:""}`:""}</p>{detail.cancelReason&&<p className="mt-2 text-sm">取消原因：{detail.cancelReason}</p>}<Button className="mt-3" variant="secondary" onClick={()=>navigate(`/business/partner-ledger?partnerId=${detail.partnerId}&direction=SUPPLIER`)}>查看供应商往来</Button>{detail.status==="POSTED"&&<Button className="mt-3 ml-2" onClick={()=>navigate(`/business/refunds?partnerId=${detail.partnerId}&direction=SUPPLIER`)}>办理退款</Button>}</>}</DetailDialog><FormDialog open={cancelTarget!==null} title={cancelTarget?.status==="POSTED"?"取消已过账采购退货":"取消采购退货草稿"} description={cancelTarget?.status==="POSTED"?"将按原明细恢复库存和供应商余额；后续退货必须先取消。":"取消草稿不会改变库存或往来余额。"} submitText="确认取消" loading={saving} submitDisabled={!reason.trim()} onCancel={()=>setCancelTarget(null)} onSubmit={cancel}><Field label="取消原因" required><Textarea value={reason} onChange={e=>setReason(e.target.value)} maxLength={500}/></Field></FormDialog></div>
}

function scaled(value:string,scale:number):bigint|null{if(!/^\d+(?:\.\d+)?$/.test(value))return null;const [whole,fraction=""]=value.split(".");if(fraction.length>scale)return null;return BigInt(whole)*BigInt(10**scale)+BigInt((fraction+"0".repeat(scale)).slice(0,scale)||"0")}
function centsText(cents:bigint):string{const whole=cents/100n;const fraction=(cents%100n).toString().padStart(2,"0");return `${whole}.${fraction}`}
function previewAmount(returned:string,quantity:string,unitPrice:string,priorAmount:string):string|null{const returnedMilli=scaled(returned,3);const quantityMilli=scaled(quantity,3);const priceCents=scaled(unitPrice,2);const priorCents=scaled(priorAmount,2);if(returnedMilli===null||quantityMilli===null||priceCents===null||priorCents===null)return null;const cumulative=(returnedMilli+quantityMilli)*priceCents;const rounded=(cumulative+500n)/1000n;return centsText(rounded-priorCents)}
