import { useCallback, useEffect, useState } from "react";
import { useSearchParams } from "react-router-dom";
import { cancelSale, createSale, getSale, partnerPage, postSale, productPage, salePage, updateSale, type PartnerRecord, type ProductRecord, type SaleDraft, type SaleInput } from "@/api/business";
import { PageHeader } from "@/components/common/page-header";
import { DataTable } from "@/components/common/data-table";
import { FormDialog } from "@/components/common/form-dialog";
import { Pagination } from "@/components/common/pagination";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import type { DataTableColumn } from "@/types";

type LineForm={id?:number;productId:number;type:"GOODS"|"SERVICE";quantity:string;price:string;remark:string};
const emptyLine=():LineForm=>({productId:0,type:"GOODS",quantity:"1",price:"0.00",remark:""});
const today=()=>new Date().toISOString().slice(0,10);

export function SalesPage(){
 const [searchParams]=useSearchParams();
 const [records,setRecords]=useState<SaleDraft[]>([]),[partners,setPartners]=useState<PartnerRecord[]>([]),[products,setProducts]=useState<ProductRecord[]>([]);
 const [page,setPage]=useState(1),[total,setTotal]=useState(0),[reload,setReload]=useState(0),[error,setError]=useState(""),[loading,setLoading]=useState(false);
 const [open,setOpen]=useState(false),[saving,setSaving]=useState(false),[editing,setEditing]=useState<SaleDraft|null>(null),[detail,setDetail]=useState<SaleDraft|null>(null);
 const [partnerId,setPartnerId]=useState(0),[businessDate,setBusinessDate]=useState(today()),[contact,setContact]=useState(""),[phone,setPhone]=useState(""),[address,setAddress]=useState(""),[remark,setRemark]=useState(""),[lines,setLines]=useState<LineForm[]>([emptyLine()]);
 const [documentNo,setDocumentNo]=useState(""),[status,setStatus]=useState(""),[filterPartner,setFilterPartner]=useState(""),[filterProduct,setFilterProduct]=useState(""),[businessFrom,setBusinessFrom]=useState(""),[businessTo,setBusinessTo]=useState("");
 const load=useCallback(()=>{setLoading(true);void salePage({page,pageSize:10,documentNo,status,partnerId:filterPartner,productId:filterProduct,businessFrom,businessTo}).then(r=>{setRecords(r.records);setTotal(r.total);setError("")}).catch((e:unknown)=>setError(e instanceof Error?e.message:"销售单加载失败")).finally(()=>setLoading(false))},[page,documentNo,status,filterPartner,filterProduct,businessFrom,businessTo]);
 useEffect(()=>{void partnerPage({page:1,pageSize:500,identity:"CUSTOMER",status:1}).then(r=>setPartners(r.records)).catch(()=>setPartners([]));void productPage({page:1,pageSize:500,status:1}).then(r=>setProducts(r.records.filter(p=>p.status===1))).catch(()=>setProducts([]))},[]);
 useEffect(()=>load(),[load,reload]);
 const linkedSaleId=searchParams.get("saleId")??"";
 useEffect(()=>{if(!linkedSaleId)return;void getSale(Number(linkedSaleId)).then(setDetail).catch((e:unknown)=>setError(e instanceof Error?e.message:"读取销售来源单失败"))},[linkedSaleId]);
 function newDraft(){setEditing(null);setPartnerId(0);setBusinessDate(today());setContact("");setPhone("");setAddress("");setRemark("");setLines([emptyLine()]);setError("");setOpen(true)}
 function editDraft(d:SaleDraft){setEditing(d);setPartnerId(d.partnerId);setBusinessDate(d.businessDate);setContact(d.deliveryContact??"");setPhone(d.deliveryPhone??"");setAddress(d.deliveryAddress??"");setRemark(d.remark??"");setLines(d.items.map(x=>({id:x.id,productId:x.productId,type:x.productType,quantity:x.quantity,price:x.unitPrice,remark:x.remark??""})));setOpen(true)}
 function setLine(i:number,patch:Partial<LineForm>){setLines(v=>v.map((x,n)=>n===i?{...x,...patch}:x))}
 async function save(){const body:SaleInput={partnerId,businessDate,deliveryContact:contact.trim()||undefined,deliveryPhone:phone.trim()||undefined,deliveryAddress:address.trim()||undefined,remark:remark.trim()||undefined,items:lines.map(l=>({id:l.id,productId:l.productId,productType:l.type,unit:products.find(p=>p.id===l.productId)?.unit??"",quantity:l.quantity,unitPrice:l.price,remark:l.remark.trim()||undefined}))};setSaving(true);try{if(editing)await updateSale(editing.id,{...body,version:editing.version});else await createSale(body);setOpen(false);setReload(v=>v+1)}catch(e){setError(e instanceof Error?e.message:"保存失败，表单输入已保留")}finally{setSaving(false)}}
 async function cancel(d:SaleDraft){const reason=window.prompt("请输入取消原因");if(!reason?.trim())return;try{await cancelSale(d.id,{version:d.version,reason});setReload(v=>v+1)}catch(e){setError(e instanceof Error?e.message:"取消失败")}}
 async function post(d:SaleDraft){const goods=new Map<string,number>();for(const i of d.items)if(i.productType==="GOODS")goods.set(i.productName,(goods.get(i.productName)??0)+Number(i.quantity));const impact=[...goods].map(([name,n])=>`${name}：-${n}`).join("\n")||"无实物库存变化";if(!window.confirm(`确认过账 ${d.documentNo}？\n客户应收增加 ¥${d.totalAmount}\n${impact}`))return;try{const posted=await postSale(d.id,d.version);setDetail(posted);setReload(v=>v+1)}catch(e){setError(e instanceof Error?e.message:"过账失败，单据内容已保留")}}
 const columns:DataTableColumn<SaleDraft>[]=[{title:"单号",dataIndex:"documentNo"},{title:"客户",dataIndex:"partnerName"},{title:"业务日期",dataIndex:"businessDate"},{title:"状态",dataIndex:"status",render:v=>v==="DRAFT"?"草稿":v==="POSTED"?"已过账":"已取消"},{title:"金额",dataIndex:"totalAmount",render:v=>`¥${v}`},{title:"操作",dataIndex:"id",render:(_,r)=><div className="flex gap-2"><Button size="sm" variant="secondary" onClick={()=>setDetail(r)}>详情</Button>{r.status==="DRAFT"&&<><Button size="sm" variant="secondary" onClick={()=>editDraft(r)}>编辑</Button><Button size="sm" onClick={()=>void post(r)}>过账</Button><Button size="sm" variant="secondary" onClick={()=>void cancel(r)}>取消</Button></>}{r.status==="POSTED"&&<Button size="sm" variant="secondary" onClick={()=>void cancel(r)}>取消已过账单</Button>}</div>}];
 return <div className="space-y-4"><PageHeader title="销售出库" description="维护客户交付草稿；草稿不改变库存或应收。" actions={<Button onClick={newDraft}>新建销售草稿</Button>}/>
  {error&&<div role="alert" className="rounded border border-red-300 p-3 text-red-700">{error}</div>}
  <div className="flex flex-wrap gap-2"><Input className="max-w-xs" placeholder="销售单号" value={documentNo} onChange={e=>setDocumentNo(e.target.value)}/><select className="rounded border px-3" aria-label="客户筛选" value={filterPartner} onChange={e=>setFilterPartner(e.target.value)}><option value="">全部客户</option>{partners.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><select className="rounded border px-3" aria-label="商品或服务筛选" value={filterProduct} onChange={e=>setFilterProduct(e.target.value)}><option value="">全部商品/服务</option>{products.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><select className="rounded border px-3" value={status} onChange={e=>setStatus(e.target.value)}><option value="">全部状态</option><option value="DRAFT">草稿</option><option value="POSTED">已过账</option><option value="CANCELLED">已取消</option></select><Input aria-label="业务日期起" type="date" value={businessFrom} onChange={e=>setBusinessFrom(e.target.value)}/><Input aria-label="业务日期止" type="date" value={businessTo} onChange={e=>setBusinessTo(e.target.value)}/><Button variant="secondary" onClick={()=>{setPage(1);setReload(v=>v+1)}}>查询</Button></div>
  <DataTable<SaleDraft> columns={columns} dataSource={records} loading={loading} rowKey="id" empty="暂无销售单"/><Pagination page={page} pageSize={10} total={total} onPageChange={setPage}/>
  <FormDialog open={open} title={editing?"编辑销售草稿":"新建销售草稿"} description="实物商品和服务可混合录入；请确认本次送货资料。" loading={saving} onCancel={()=>setOpen(false)} onSubmit={save}>
   <div className="grid gap-3 md:grid-cols-2"><label className="grid gap-1 text-sm">客户<select className="rounded border px-3 py-2" value={partnerId} onChange={e=>{const id=Number(e.target.value),p=partners.find(x=>x.id===id);setPartnerId(id);setContact(p?.contact??"");setPhone(p?.phone??"");setAddress(p?.address??"")}}><option value={0}>请选择客户</option>{partners.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label className="grid gap-1 text-sm">业务日期<Input type="date" value={businessDate} onChange={e=>setBusinessDate(e.target.value)}/></label><label className="grid gap-1 text-sm">送货联系人<Input value={contact} onChange={e=>setContact(e.target.value)}/></label><label className="grid gap-1 text-sm">送货电话<Input value={phone} onChange={e=>setPhone(e.target.value)}/></label><label className="grid gap-1 text-sm md:col-span-2">送货地址<Input value={address} onChange={e=>setAddress(e.target.value)}/></label></div>
   <div className="mt-4 space-y-2"><div className="flex items-center justify-between"><strong>销售明细</strong><Button type="button" variant="secondary" onClick={()=>setLines(v=>[...v,emptyLine()])}>增加明细</Button></div>{lines.map((l,i)=><div className="grid gap-2 rounded border p-3 md:grid-cols-5" key={i}><select className="rounded border px-2" value={l.productId} onChange={e=>{const id=Number(e.target.value),p=products.find(x=>x.id===id);setLine(i,{productId:id,type:p?.type??"GOODS",price:p?.salePrice??"0.00"})}}><option value={0}>选择商品或服务</option>{products.map(p=><option key={p.id} value={p.id}>{p.name}（{p.type==="SERVICE"?"服务":"实物"}）</option>)}</select><Input aria-label="数量" value={l.quantity} onChange={e=>setLine(i,{quantity:e.target.value})}/><Input aria-label="成交单价" value={l.price} onChange={e=>setLine(i,{price:e.target.value})}/><Input aria-label="说明" value={l.remark} onChange={e=>setLine(i,{remark:e.target.value})}/><Button type="button" variant="secondary" disabled={lines.length===1} onClick={()=>setLines(v=>v.filter((_,n)=>n!==i))}>移除</Button></div>)}</div>
   <label className="mt-4 grid gap-1 text-sm">备注<Textarea value={remark} onChange={e=>setRemark(e.target.value)}/></label>
  </FormDialog>
  {detail&&<div role="dialog" className="fixed inset-0 z-40 grid place-items-center bg-black/30 p-4" onClick={()=>setDetail(null)}><div className="max-h-[90vh] w-full max-w-2xl overflow-auto rounded bg-white p-6" onClick={e=>e.stopPropagation()}><div className="flex justify-between"><h2 className="text-lg font-semibold">销售单 {detail.documentNo}</h2><Button variant="secondary" onClick={()=>setDetail(null)}>关闭</Button></div><p>{detail.partnerName} · {detail.businessDate} · {detail.status}</p><p>送货：{detail.deliveryContact??""} / {detail.deliveryPhone??""} / {detail.deliveryAddress??""}</p>{detail.status!=="CANCELLED"&&<Button variant="secondary" onClick={()=>{window.location.href=`/business/sales/${detail.id}/delivery-note`}}>打印送货单</Button>}{detail.status!=="DRAFT"&&detail.status!=="CANCELLED"&&<Button variant="secondary" onClick={()=>{window.location.href=`/business/sale-returns?saleId=${detail.id}`}}>办理退货</Button>}{detail.status!=="DRAFT"&&<p>经营者：{detail.ownerName} / {detail.ownerPhone} / {detail.ownerAddress}</p>}{detail.items.map(i=><p key={i.id}>{i.productCode} {i.productName}（{i.productModel??""} {i.productSpecification??""}，{i.unit}，{i.productType==="SERVICE"?"服务":"实物"}） {i.quantity} × ¥{i.unitPrice} = ¥{i.amount}</p>)}<strong>合计 ¥{detail.totalAmount}</strong>{detail.postedAt&&<p>过账：{detail.postedByName} · {new Date(detail.postedAt).toLocaleString()}</p>}{detail.cancelReason&&<p>取消原因：{detail.cancelReason}</p>}</div></div>}
 </div>
}
