import { useCallback, useEffect, useState } from "react";
import { useNavigate, useSearchParams } from "react-router-dom";
import { cancelSaleReturn, createSaleReturn, getSaleReturn, getSaleReturnSource, postSaleReturn, saleReturnPage, updateSaleReturn, type SaleReturn, type SaleReturnSource } from "@/api/business";
import { DataTable } from "@/components/common/data-table";
import { DataTableCard } from "@/components/common/data-table-card";
import { DetailDialog } from "@/components/common/detail-dialog";
import { Field } from "@/components/common/field";
import { FormDialog } from "@/components/common/form-dialog";
import { PageHeader } from "@/components/common/page-header";
import { Pagination } from "@/components/common/pagination";
import { SearchFilterBar } from "@/components/common/search-filter-bar";
import { TableToolbar } from "@/components/common/table-toolbar";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import type { DataTableColumn } from "@/types";

type Line = {saleItemId:number;quantity:string;remark?:string};
const today=()=>{const d=new Date();return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10)};
export function SaleReturnsPage(){
 const navigate=useNavigate();const [params]=useSearchParams();const [page,setPage]=useState(1);const [rows,setRows]=useState<SaleReturn[]>([]);const [total,setTotal]=useState(0);const [filters,setFilters]=useState({documentNo:"",saleId:"",partnerId:"",status:"",businessFrom:"",businessTo:""});const [query,setQuery]=useState(filters);const [loading,setLoading]=useState(false);const [error,setError]=useState("");const [reload,setReload]=useState(0);
 const [source,setSource]=useState<SaleReturnSource|null>(null);const [editing,setEditing]=useState<SaleReturn|null>(null);const [open,setOpen]=useState(false);const [date,setDate]=useState(today());const [remark,setRemark]=useState("");const [lines,setLines]=useState<Line[]>([]);const [saving,setSaving]=useState(false);const [detail,setDetail]=useState<SaleReturn|null>(null);const [cancelTarget,setCancelTarget]=useState<SaleReturn|null>(null);const [reason,setReason]=useState("");
 const load=useCallback(()=>{setLoading(true);void saleReturnPage({page,pageSize:10,...query}).then(x=>{setRows(x.records);setTotal(x.total);setError("")}).catch(e=>setError(e instanceof Error?e.message:"销售退货加载失败")).finally(()=>setLoading(false))},[page,query]);useEffect(()=>load(),[load,reload]);
 async function startCreate(saleId:number){try{const s=await getSaleReturnSource(saleId);setSource(s);setEditing(null);setDate(today());setRemark("");setLines(s.items.map(i=>({saleItemId:i.saleItemId,quantity:"0"})));setOpen(true);setError("")}catch(e){setError(e instanceof Error?e.message:"读取原销售单失败")}}
 async function startEdit(row:SaleReturn){try{const d=await getSaleReturn(row.id);const s=await getSaleReturnSource(d.saleId);setSource(s);setEditing(d);setDate(d.businessDate);setRemark(d.remark??"");setLines(d.items.map(i=>({saleItemId:i.saleItemId,quantity:i.quantity,remark:i.remark??undefined})));setOpen(true)}catch(e){setError(e instanceof Error?e.message:"读取草稿失败")}}
 useEffect(()=>{const id=Number(params.get("saleId"));if(id>0)void startCreate(id)},[params]);
 useEffect(()=>{const id=Number(params.get("saleReturnId"));if(id>0)void getSaleReturn(id).then(setDetail).catch(e=>setError(e instanceof Error?e.message:"读取销售退货来源单失败"))},[params]);
 async function save(){if(!source)return;setSaving(true);try{const input={saleId:source.saleId,businessDate:date,remark:remark.trim()||undefined,items:lines.filter(x=>Number(x.quantity)>0).map(({saleItemId,quantity,remark:r})=>({saleItemId,quantity,remark:r}))};if(!input.items.length)throw new Error("请至少填写一行退货数量");if(editing)await updateSaleReturn(editing.id,{...input,version:editing.version});else await createSaleReturn(input);setOpen(false);setReload(x=>x+1)}catch(e){setError(e instanceof Error?e.message:"保存失败，表单内容已保留")}finally{setSaving(false)}}
 async function cancel(){if(!cancelTarget)return;setSaving(true);try{await cancelSaleReturn(cancelTarget.id,{version:cancelTarget.version,reason});setCancelTarget(null);setReload(x=>x+1)}catch(e){setError(e instanceof Error?e.message:"取消失败")}finally{setSaving(false)}}
 async function post(row:SaleReturn){setSaving(true);try{await postSaleReturn(row.id,{version:row.version});setReload(x=>x+1);setError("")}catch(e){setError(e instanceof Error?e.message:"过账失败，请刷新后重试")}finally{setSaving(false)}}
 const columns:DataTableColumn<SaleReturn>[]=[{title:"退货单号",dataIndex:"documentNo"},{title:"原销售单",dataIndex:"saleNo"},{title:"客户",dataIndex:"partnerName"},{title:"业务日期",dataIndex:"businessDate"},{title:"单据金额",dataIndex:"totalAmount",align:"right",render:v=>`¥${v}`},{title:"状态",dataIndex:"status",render:v=>({DRAFT:"草稿",POSTED:"已过账",CANCELLED:"已取消"}[String(v)]??String(v))},{title:"操作",key:"actions",render:(_,r)=><div className="flex gap-2"><Button size="sm" variant="secondary" onClick={()=>void getSaleReturn(r.id).then(setDetail).catch(e=>setError(e.message))}>查看</Button>{r.status==="DRAFT"&&<><Button size="sm" variant="secondary" onClick={()=>void startEdit(r)}>编辑</Button><Button size="sm" variant="secondary" onClick={()=>void post(r)}>过账</Button><Button size="sm" variant="secondary" onClick={()=>{setCancelTarget(r);setReason("")}}>取消</Button></>}{r.status==="POSTED"&&<Button size="sm" variant="secondary" onClick={()=>{setCancelTarget(r);setReason("")}}>冲销取消</Button>}</div>}];
 return <div className="space-y-space-4"><PageHeader title="销售退货" description="退货过账会整单增加库存并抵减客户欠款；草稿不改变库存或客户应收。取消已过账退货会按原金额、原数量冲回，同一原明细须按退货过账逆序取消。" actions={<Button onClick={()=>{const id=Number(params.get("saleId"));if(id>0)void startCreate(id);else setError("请从已过账销售单点击“办理退货”。")}}>新建退货草稿</Button>}/><SearchFilterBar actions={<><Button onClick={()=>{setPage(1);setQuery({...filters})}}>查询</Button><Button variant="secondary" onClick={()=>{const empty={documentNo:"",saleId:"",partnerId:"",status:"",businessFrom:"",businessTo:""};setFilters(empty);setQuery(empty);setPage(1)}}>重置</Button></>}>
 <Field label="退货单号"><Input value={filters.documentNo} onChange={e=>setFilters({...filters,documentNo:e.target.value})} placeholder="输入单号"/></Field>
 <Field label="原销售单ID"><Input inputMode="numeric" value={filters.saleId} onChange={e=>setFilters({...filters,saleId:e.target.value})}/></Field>
 <Field label="客户ID"><Input inputMode="numeric" value={filters.partnerId} onChange={e=>setFilters({...filters,partnerId:e.target.value})}/></Field>
 <Field label="状态"><select className="h-control w-full rounded-control border border-border bg-surface px-space-3" value={filters.status} onChange={e=>setFilters({...filters,status:e.target.value})}><option value="">全部状态</option><option value="DRAFT">草稿</option><option value="POSTED">已过账</option><option value="CANCELLED">已取消</option></select></Field>
 <Field label="业务日期起"><Input type="date" value={filters.businessFrom} onChange={e=>setFilters({...filters,businessFrom:e.target.value})}/></Field><Field label="业务日期止"><Input type="date" value={filters.businessTo} onChange={e=>setFilters({...filters,businessTo:e.target.value})}/></Field>
 </SearchFilterBar>{error&&<p role="alert" className="text-sm text-error">{error}</p>}<DataTableCard toolbar={<TableToolbar title="销售退货单" description="按来源销售单查看单据；草稿不预占原销售明细的退货额度；提交时按当前已过账退货展示。"/>} pagination={<Pagination page={page} pageSize={10} total={total} disabled={loading} onPageChange={setPage}/>}><DataTable columns={columns} dataSource={rows} rowKey="id" loading={loading} minWidth={900} empty="暂无销售退货单。"/></DataTableCard>
 <FormDialog open={open} title={editing?`编辑销售退货草稿 · ${editing.documentNo}`:"新建销售退货草稿"} description={source?`原单 ${source.saleNo} · ${source.partnerName} · 编辑版本 ${editing?.version??1}`:undefined} loading={saving} onCancel={()=>setOpen(false)} onSubmit={save}>{error&&<p role="alert" className="mb-3 text-sm text-error">{error}</p>}<div className="grid gap-space-3 md:grid-cols-2"><Field label="业务日期" required><Input type="date" value={date} onChange={e=>setDate(e.target.value)}/></Field><Field label="备注"><Input value={remark} onChange={e=>setRemark(e.target.value)} maxLength={500}/></Field></div><div className="mt-space-4 space-y-3">{source?.items.map((item,index)=>{const line=lines[index];const amount=previewAmount(item.returnedQuantity,line?.quantity??"0",item.unitPrice,item.priorReturnAmount);return <div key={item.saleItemId} className="rounded-control border border-border p-space-3"><p className="font-medium">{item.productCode} · {item.productName} {item.productModel||""} {item.productSpecification||""}</p><p className="text-sm text-text-tertiary">原数量 {item.originalQuantity} {item.unit} · 已过账退货 {item.returnedQuantity} · 剩余额度 {item.remainingQuantity} · 原单价 ¥{item.unitPrice} · 此前退货金额 ¥{item.priorReturnAmount}</p><div className="mt-2 grid gap-2 md:grid-cols-2"><Field label="本次退货数量"><Input inputMode="decimal" value={line?.quantity??"0"} onChange={e=>setLines(v=>v.map((x,i)=>i===index?{...x,quantity:e.target.value}:x))}/></Field><p className="self-end pb-2 text-sm">累计取整差额预览：{amount===null?"—":`¥${amount}`}</p></div></div>})}</div><p className="mt-3 text-xs text-text-tertiary">停用商品和客户的历史退货仍可办理。草稿不会改变库存、客户应收或已生效退货额度。</p></FormDialog>
 <DetailDialog open={detail!==null} title={detail?`销售退货 · ${detail.documentNo}`:"销售退货详情"} description={detail?`原单 ${detail.saleNo} · ${detail.partnerName} · ${detail.status}`:undefined} onCancel={()=>setDetail(null)}>{detail&&<><DataTable columns={[{title:"原销售明细ID",dataIndex:"saleItemId"},{title:"商品快照",key:"product",render:(_,i)=>`${i.productCode} ${i.productName}`},{title:"原数量/累计退货/剩余",key:"quota",render:(_,i)=>`${i.originalQuantity} / ${i.returnedQuantity} / ${i.remainingQuantity}`},{title:"本次数量",dataIndex:"quantity"},{title:"原价",dataIndex:"unitPrice"},{title:"退货金额",dataIndex:"amount"}]} dataSource={detail.items} rowKey="id" minWidth={760}/><p className="mt-3 text-right">退货金额：¥{detail.totalAmount}</p><p className="mt-2 text-sm text-text-tertiary">创建人：{detail.createdByName} · 创建时间：{new Date(detail.createTime).toLocaleString()}{detail.postedByName?` · 过账人：${detail.postedByName}${detail.postedAt?` · ${new Date(detail.postedAt).toLocaleString()}`:""}`:""}{detail.cancelledByName?` · 取消人：${detail.cancelledByName}${detail.cancelledAt?` · ${new Date(detail.cancelledAt).toLocaleString()}`:""}`:""}</p>{detail.cancelReason&&<p className="mt-2 text-sm">取消原因：{detail.cancelReason}</p>}<Button className="mt-3" variant="secondary" onClick={()=>navigate(`/business/partner-balances?partnerId=${detail.partnerId}&direction=CUSTOMER`)}>查看客户往来</Button></>}</DetailDialog><FormDialog open={cancelTarget!==null} title={cancelTarget?.status==="POSTED"?"取消已过账销售退货":"取消销售退货草稿"} description={cancelTarget?.status==="POSTED"?"将按原明细扣回库存并恢复客户欠款；同一原明细的后续退货必须先取消。":"取消草稿不会改变库存或往来余额。"} submitText="确认取消" loading={saving} submitDisabled={!reason.trim()} onCancel={()=>setCancelTarget(null)} onSubmit={cancel}><Field label="取消原因" required><Textarea value={reason} onChange={e=>setReason(e.target.value)} maxLength={500}/></Field></FormDialog></div>
}

function scaled(value:string,scale:number):bigint|null{if(!/^\d+(?:\.\d+)?$/.test(value))return null;const [whole,fraction=""]=value.split(".");if(fraction.length>scale)return null;return BigInt(whole)*BigInt(10**scale)+BigInt((fraction+"0".repeat(scale)).slice(0,scale)||"0")}
function centsText(cents:bigint):string{const whole=cents/100n;const fraction=(cents%100n).toString().padStart(2,"0");return `${whole}.${fraction}`}
function previewAmount(returned:string,quantity:string,unitPrice:string,priorAmount:string):string|null{const returnedMilli=scaled(returned,3);const quantityMilli=scaled(quantity,3);const priceCents=scaled(unitPrice,2);const priorCents=scaled(priorAmount,2);if(returnedMilli===null||quantityMilli===null||priceCents===null||priorCents===null)return null;const cumulative=(returnedMilli+quantityMilli)*priceCents;const rounded=(cumulative+500n)/1000n;return centsText(rounded-priorCents)}
