"""Validate physical pages and text geometry in PDFs generated by the browser."""
import json
from pathlib import Path
import subprocess
import sys
import xml.etree.ElementTree as ET

output = Path(sys.argv[1])
results = json.loads((output / "result.json").read_text())
ns = {"x": "http://www.w3.org/1999/xhtml"}
for result in results:
    xml = subprocess.check_output(["pdftotext", "-bbox", str(output / (result["name"] + ".pdf")), "-"], text=True)
    pages = ET.fromstring(xml).findall(".//x:page", ns)
    assert len(pages) == result["pages"], (result["name"], len(pages), result["pages"])
    texts = []
    for index, page in enumerate(pages):
        width, height = float(page.attrib["width"]), float(page.attrib["height"])
        assert abs(width - 595.28) < 1 and abs(height - 841.89) < 1
        words = page.findall(".//x:word", ns)
        text = "".join(word.text or "" for word in words)
        texts.append(text)
        assert f"第{index + 1}/{len(pages)}页" in text, (result["name"], index, text[-150:])
        for word in words:
            x1, x2 = float(word.attrib["xMin"]), float(word.attrib["xMax"])
            y1, y2 = float(word.attrib["yMin"]), float(word.attrib["yMax"])
            # Font bounding boxes can exceed their CSS line boxes; verify that
            # every extracted fragment remains inside the physical A4 sheet.
            assert x1 >= 0 and x2 <= width + 1, (result["name"], word.text, word.attrib)
            assert y1 >= 0 and y2 <= height + 1, (result["name"], word.text, word.attrib)
    assert result["lastText"] in texts[-1], (result["name"], texts[-1])
    assert all(result["lastText"] not in text for text in texts[:-1])
    if result["hidden"]:
        assert "¥" not in "".join(texts) and "合计金额" not in "".join(texts)
    if not result["statement"]:
        # Extract all fragments of the long document number and ensure they share
        # one baseline. The footer repeats it, so inspect the upper half only.
        for page in pages:
            fragments = [w for w in page.findall(".//x:word", ns) if (w.text or "").startswith("单号：SO20261002-") and float(w.attrib["yMin"]) < 350]
            assert len(fragments) == 1, (result["name"], fragments)
            assert fragments[0].text == "单号：SO20261002-040ba5bc329641dc373e0123456789ab"
print(json.dumps([{"file": item["name"], "a4Pages": item["pages"]} for item in results], ensure_ascii=False))
