-- +goose Up
CREATE TABLE sys_oper_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module_name VARCHAR(100) NOT NULL,
    operation_type VARCHAR(50) NOT NULL,
    request_id VARCHAR(128),
    request_method VARCHAR(20),
    request_url VARCHAR(500),
    operator_id BIGINT,
    operator_name VARCHAR(50),
    operator_ip VARCHAR(45),
    operator_location VARCHAR(100),
    user_agent VARCHAR(500),
    request_params TEXT,
    response_result TEXT,
    cost_time BIGINT,
    operation_status VARCHAR(20) NOT NULL,
    error_message TEXT,
    operation_time TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    create_time TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_sys_oper_log_module_not_blank CHECK (length(trim(module_name)) > 0),
    CONSTRAINT ck_sys_oper_log_type_not_blank CHECK (length(trim(operation_type)) > 0),
    CONSTRAINT ck_sys_oper_log_cost_time CHECK (cost_time IS NULL OR cost_time >= 0),
    CONSTRAINT ck_sys_oper_log_status CHECK (operation_status IN ('SUCCESS', 'FAIL'))
);

CREATE INDEX idx_sys_oper_log_module_name ON sys_oper_log (module_name);
CREATE INDEX idx_sys_oper_log_operation_type ON sys_oper_log (operation_type);
CREATE INDEX idx_sys_oper_log_request_id ON sys_oper_log (request_id);
CREATE INDEX idx_sys_oper_log_operator_id ON sys_oper_log (operator_id);
CREATE INDEX idx_sys_oper_log_status ON sys_oper_log (operation_status);
CREATE INDEX idx_sys_oper_log_time ON sys_oper_log (operation_time);

-- +goose Down
DROP TABLE IF EXISTS sys_oper_log;
