-- +goose Up
CREATE TABLE product (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 code VARCHAR(50) NOT NULL UNIQUE, name VARCHAR(200) NOT NULL, type VARCHAR(20) NOT NULL,
 brand VARCHAR(100), model VARCHAR(100), specification VARCHAR(200), category VARCHAR(100),
 unit VARCHAR(50) NOT NULL, purchase_price_cents BIGINT, sale_price_cents BIGINT,
 remark VARCHAR(500), status SMALLINT NOT NULL DEFAULT 1,
 create_time TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
 update_time TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT ck_product_type CHECK(type IN ('GOODS','SERVICE')),
 CONSTRAINT ck_product_status CHECK(status IN (0,1)),
 CONSTRAINT ck_product_prices CHECK((purchase_price_cents IS NULL OR purchase_price_cents >= 0) AND (sale_price_cents IS NULL OR sale_price_cents >= 0))
);
CREATE INDEX idx_product_status_type_id ON product(status,type,id);
CREATE INDEX idx_product_category ON product(category);

CREATE TABLE partner (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 code VARCHAR(50) NOT NULL UNIQUE, name VARCHAR(200) NOT NULL, type VARCHAR(20) NOT NULL,
 is_customer BOOLEAN NOT NULL, is_supplier BOOLEAN NOT NULL,
 contact VARCHAR(100), phone VARCHAR(50), address VARCHAR(500), remark VARCHAR(500),
 invoice_name VARCHAR(200), tax_number VARCHAR(100), registered_address VARCHAR(500),
 registered_phone VARCHAR(50), bank_name VARCHAR(200), bank_account VARCHAR(100),
 status SMALLINT NOT NULL DEFAULT 1,
 create_time TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
 update_time TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT ck_partner_type CHECK(type IN ('COMPANY','PERSON')),
 CONSTRAINT ck_partner_roles CHECK(is_customer OR is_supplier),
 CONSTRAINT ck_partner_status CHECK(status IN (0,1))
);
CREATE INDEX idx_partner_status_type_id ON partner(status,type,id);

CREATE TABLE warehouse (
 singleton_id SMALLINT PRIMARY KEY CHECK(singleton_id=1),
 name VARCHAR(100) NOT NULL, remark VARCHAR(500),
 update_time TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
-- +goose Down
DROP TABLE IF EXISTS warehouse;
DROP TABLE IF EXISTS partner;
DROP TABLE IF EXISTS product;
