-- +goose Up
CREATE TABLE sys_dict_type (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dict_name VARCHAR(100) NOT NULL,
    dict_code VARCHAR(100) NOT NULL,
    status SMALLINT NOT NULL DEFAULT 1,
    sort_order INTEGER NOT NULL DEFAULT 0,
    is_builtin SMALLINT NOT NULL DEFAULT 0,
    remark VARCHAR(500),
    create_time TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    create_by BIGINT,
    update_by BIGINT,
    deleted SMALLINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_sys_dict_type_code UNIQUE (dict_code),
    CONSTRAINT ck_sys_dict_type_name_not_blank CHECK (length(trim(dict_name)) > 0),
    CONSTRAINT ck_sys_dict_type_code_not_blank CHECK (length(trim(dict_code)) > 0),
    CONSTRAINT ck_sys_dict_type_status CHECK (status IN (0, 1)),
    CONSTRAINT ck_sys_dict_type_is_builtin CHECK (is_builtin IN (0, 1)),
    CONSTRAINT ck_sys_dict_type_deleted CHECK (deleted IN (0, 1))
);

CREATE INDEX idx_sys_dict_type_deleted_status_sort
    ON sys_dict_type (deleted, status, sort_order);

CREATE TABLE sys_dict_data (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dict_type_id BIGINT NOT NULL,
    dict_label VARCHAR(100) NOT NULL,
    dict_value VARCHAR(100) NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    remark VARCHAR(500),
    create_time TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    create_by BIGINT,
    update_by BIGINT,
    deleted SMALLINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_sys_dict_data_type_value UNIQUE (dict_type_id, dict_value),
    CONSTRAINT fk_sys_dict_data_type FOREIGN KEY (dict_type_id) REFERENCES sys_dict_type (id) ON DELETE RESTRICT,
    CONSTRAINT ck_sys_dict_data_label_not_blank CHECK (length(trim(dict_label)) > 0),
    CONSTRAINT ck_sys_dict_data_value_not_blank CHECK (length(trim(dict_value)) > 0),
    CONSTRAINT ck_sys_dict_data_deleted CHECK (deleted IN (0, 1))
);

CREATE INDEX idx_sys_dict_data_type_id ON sys_dict_data (dict_type_id);
CREATE INDEX idx_sys_dict_data_deleted_sort ON sys_dict_data (deleted, sort_order);

CREATE TABLE sys_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    config_name VARCHAR(100) NOT NULL,
    config_key VARCHAR(100) NOT NULL,
    config_value VARCHAR(500),
    config_type VARCHAR(20) NOT NULL DEFAULT 'SYSTEM',
    value_type VARCHAR(20) NOT NULL DEFAULT 'TEXT',
    status SMALLINT NOT NULL DEFAULT 1,
    is_builtin SMALLINT NOT NULL DEFAULT 0,
    remark VARCHAR(500),
    create_time TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    create_by BIGINT,
    update_by BIGINT,
    deleted SMALLINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_sys_config_key UNIQUE (config_key),
    CONSTRAINT ck_sys_config_name_not_blank CHECK (length(trim(config_name)) > 0),
    CONSTRAINT ck_sys_config_key_not_blank CHECK (length(trim(config_key)) > 0),
    CONSTRAINT ck_sys_config_type_not_blank CHECK (length(trim(config_type)) > 0),
    CONSTRAINT ck_sys_config_value_type_not_blank CHECK (length(trim(value_type)) > 0),
    CONSTRAINT ck_sys_config_status CHECK (status IN (0, 1)),
    CONSTRAINT ck_sys_config_is_builtin CHECK (is_builtin IN (0, 1)),
    CONSTRAINT ck_sys_config_deleted CHECK (deleted IN (0, 1))
);

CREATE INDEX idx_sys_config_type ON sys_config (config_type);
CREATE INDEX idx_sys_config_deleted_status ON sys_config (deleted, status);

-- +goose Down
DROP TABLE IF EXISTS sys_config;
DROP TABLE IF EXISTS sys_dict_data;
DROP TABLE IF EXISTS sys_dict_type;
