-- +goose Up
CREATE TABLE purchase_document (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 document_no VARCHAR(40) NOT NULL UNIQUE,
 partner_id BIGINT NOT NULL REFERENCES partner(id),
 business_date DATE NOT NULL,
 status VARCHAR(20) NOT NULL CHECK(status IN ('DRAFT','CANCELLED')),
 version BIGINT NOT NULL CHECK(version > 0),
 remark VARCHAR(500),
 created_by BIGINT NOT NULL REFERENCES sys_user(id),
 create_time TIMESTAMP WITH TIME ZONE NOT NULL,
 cancelled_by BIGINT REFERENCES sys_user(id),
 cancelled_at TIMESTAMP WITH TIME ZONE,
 cancel_reason VARCHAR(500),
 CHECK((status='DRAFT' AND cancelled_by IS NULL AND cancelled_at IS NULL AND cancel_reason IS NULL) OR (status='CANCELLED' AND cancelled_by IS NOT NULL AND cancelled_at IS NOT NULL AND length(trim(cancel_reason))>0))
);
CREATE INDEX idx_purchase_document_partner_date ON purchase_document(partner_id,business_date,id);
CREATE INDEX idx_purchase_document_status_id ON purchase_document(status,id);
CREATE TABLE purchase_document_item (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 document_id BIGINT NOT NULL REFERENCES purchase_document(id),
 product_id BIGINT NOT NULL REFERENCES product(id),
 product_code VARCHAR(50) NOT NULL,
 product_name VARCHAR(200) NOT NULL,
 product_model VARCHAR(100),
 product_specification VARCHAR(200),
 product_type VARCHAR(20) NOT NULL CHECK(product_type='GOODS'),
 unit VARCHAR(50) NOT NULL CHECK(length(trim(unit))>0),
 quantity_milli BIGINT NOT NULL CHECK(quantity_milli>0),
 unit_price_cents BIGINT NOT NULL CHECK(unit_price_cents>=0),
 amount_cents BIGINT NOT NULL CHECK(amount_cents>=0),
 remark VARCHAR(500)
);
CREATE INDEX idx_purchase_document_item_product ON purchase_document_item(product_id,document_id);
-- +goose Down
DROP TABLE IF EXISTS purchase_document_item;
DROP TABLE IF EXISTS purchase_document;
