-- +goose Up
CREATE TABLE sale_return_document (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 document_no VARCHAR(40) NOT NULL UNIQUE,
 sale_id BIGINT NOT NULL REFERENCES sale_document(id),
 partner_id BIGINT NOT NULL REFERENCES partner(id),
 business_date DATE NOT NULL,
 status VARCHAR(20) NOT NULL CHECK(status IN ('DRAFT','POSTED','CANCELLED')),
 version BIGINT NOT NULL CHECK(version>0),
 remark VARCHAR(500), created_by BIGINT NOT NULL REFERENCES sys_user(id), create_time TIMESTAMP WITH TIME ZONE NOT NULL,
 posted_by BIGINT REFERENCES sys_user(id), posted_at TIMESTAMP WITH TIME ZONE,
 cancelled_by BIGINT REFERENCES sys_user(id), cancelled_at TIMESTAMP WITH TIME ZONE, cancel_reason VARCHAR(500),
 CHECK((status='DRAFT' AND posted_by IS NULL AND posted_at IS NULL AND cancelled_by IS NULL AND cancelled_at IS NULL AND cancel_reason IS NULL)
  OR (status='POSTED' AND posted_by IS NOT NULL AND posted_at IS NOT NULL AND cancelled_by IS NULL AND cancelled_at IS NULL AND cancel_reason IS NULL)
  OR (status='CANCELLED' AND cancelled_by IS NOT NULL AND cancelled_at IS NOT NULL AND length(trim(cancel_reason))>0 AND ((posted_by IS NULL AND posted_at IS NULL) OR (posted_by IS NOT NULL AND posted_at IS NOT NULL))))
);
CREATE INDEX idx_sale_return_origin ON sale_return_document(sale_id,id);
CREATE INDEX idx_sale_return_partner_date ON sale_return_document(partner_id,business_date,id);
CREATE INDEX idx_sale_return_status_id ON sale_return_document(status,id);
CREATE INDEX idx_sale_return_posted ON sale_return_document(sale_id,posted_at,id);
CREATE TABLE sale_return_document_item (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 document_id BIGINT NOT NULL REFERENCES sale_return_document(id),
 sale_item_id BIGINT NOT NULL REFERENCES sale_document_item(id),
 product_id BIGINT NOT NULL REFERENCES product(id), product_code VARCHAR(50) NOT NULL, product_name VARCHAR(200) NOT NULL,
 product_model VARCHAR(100), product_specification VARCHAR(200), unit VARCHAR(50) NOT NULL CHECK(length(trim(unit))>0),
 quantity_milli BIGINT NOT NULL CHECK(quantity_milli>0), unit_price_cents BIGINT NOT NULL CHECK(unit_price_cents>=0), amount_cents BIGINT NOT NULL CHECK(amount_cents>=0), remark VARCHAR(500)
);
CREATE INDEX idx_sale_return_item_origin ON sale_return_document_item(sale_item_id,document_id);
CREATE INDEX idx_sale_return_item_document ON sale_return_document_item(document_id,id);
-- +goose Down
DROP TABLE IF EXISTS sale_return_document_item;
DROP TABLE IF EXISTS sale_return_document;
