-- +goose Up
CREATE TABLE partner_balance_entry_new (
 id INTEGER PRIMARY KEY,partner_id BIGINT NOT NULL REFERENCES partner(id),direction VARCHAR(20) NOT NULL CHECK(direction IN ('CUSTOMER','SUPPLIER')),entry_type VARCHAR(30) NOT NULL CHECK(entry_type IN ('OPENING','RECEIPT','PAYMENT','PURCHASE','SALE','PURCHASE_RETURN','SALE_RETURN','CUSTOMER_REFUND','SUPPLIER_REFUND','REVERSAL')),
 amount_cents BIGINT NOT NULL CHECK(amount_cents<>0 AND typeof(amount_cents)='integer'),balance_before_cents BIGINT NOT NULL CHECK(typeof(balance_before_cents)='integer'),balance_after_cents BIGINT NOT NULL CHECK(typeof(balance_after_cents)='integer'),business_date DATE NOT NULL,effective_at DATETIME NOT NULL,description VARCHAR(500) NOT NULL,document_no VARCHAR(40) NOT NULL UNIQUE,operator_id BIGINT NOT NULL REFERENCES sys_user(id),request_key VARCHAR(100) UNIQUE,reverses_id BIGINT REFERENCES partner_balance_entry_new(id),reversed_by_id BIGINT REFERENCES partner_balance_entry_new(id),create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,payment_method VARCHAR(20) NOT NULL DEFAULT '',transaction_no VARCHAR(100) NOT NULL DEFAULT '',purchase_id BIGINT REFERENCES purchase_document(id),sale_id BIGINT REFERENCES sale_document(id),purchase_return_id BIGINT REFERENCES purchase_return_document(id),sale_return_id BIGINT REFERENCES sale_return_document(id),
 CHECK(balance_after_cents=balance_before_cents+amount_cents),
 CHECK((entry_type='OPENING' AND amount_cents>0 AND reverses_id IS NULL AND purchase_id IS NULL AND sale_id IS NULL AND purchase_return_id IS NULL AND sale_return_id IS NULL) OR (entry_type IN ('RECEIPT','PAYMENT') AND amount_cents<0 AND reverses_id IS NULL AND purchase_id IS NULL AND sale_id IS NULL AND purchase_return_id IS NULL AND sale_return_id IS NULL) OR (entry_type IN ('CUSTOMER_REFUND','SUPPLIER_REFUND') AND ((entry_type='CUSTOMER_REFUND' AND direction='CUSTOMER') OR (entry_type='SUPPLIER_REFUND' AND direction='SUPPLIER')) AND amount_cents>0 AND reverses_id IS NULL AND purchase_id IS NULL AND sale_id IS NULL AND purchase_return_id IS NULL AND sale_return_id IS NULL) OR (entry_type='PURCHASE' AND amount_cents>0 AND reverses_id IS NULL AND purchase_id IS NOT NULL AND sale_id IS NULL AND purchase_return_id IS NULL AND sale_return_id IS NULL) OR (entry_type='SALE' AND amount_cents>0 AND reverses_id IS NULL AND purchase_id IS NULL AND sale_id IS NOT NULL AND purchase_return_id IS NULL AND sale_return_id IS NULL) OR (entry_type='PURCHASE_RETURN' AND amount_cents<0 AND reverses_id IS NULL AND purchase_id IS NULL AND sale_id IS NULL AND purchase_return_id IS NOT NULL AND sale_return_id IS NULL) OR (entry_type='SALE_RETURN' AND amount_cents<0 AND reverses_id IS NULL AND purchase_id IS NULL AND sale_id IS NULL AND purchase_return_id IS NULL AND sale_return_id IS NOT NULL) OR (entry_type='REVERSAL' AND amount_cents<>0 AND reverses_id IS NOT NULL))
);
INSERT INTO partner_balance_entry_new(id,partner_id,direction,entry_type,amount_cents,balance_before_cents,balance_after_cents,business_date,effective_at,description,document_no,operator_id,request_key,reverses_id,reversed_by_id,create_time,payment_method,transaction_no,purchase_id,sale_id,purchase_return_id,sale_return_id)
 SELECT id,partner_id,direction,entry_type,amount_cents,balance_before_cents,balance_after_cents,business_date,effective_at,description,document_no,operator_id,request_key,reverses_id,reversed_by_id,create_time,payment_method,transaction_no,purchase_id,sale_id,purchase_return_id,sale_return_id FROM partner_balance_entry;
DROP TABLE partner_balance_entry;
ALTER TABLE partner_balance_entry_new RENAME TO partner_balance_entry;
CREATE UNIQUE INDEX uk_partner_balance_reversal ON partner_balance_entry(reverses_id) WHERE reverses_id IS NOT NULL;
CREATE INDEX idx_partner_balance_entry_scope ON partner_balance_entry(partner_id,direction,effective_at,id);
CREATE UNIQUE INDEX uk_partner_balance_purchase ON partner_balance_entry(purchase_id) WHERE purchase_id IS NOT NULL;
CREATE UNIQUE INDEX uk_partner_balance_sale ON partner_balance_entry(sale_id) WHERE sale_id IS NOT NULL;
CREATE UNIQUE INDEX uk_partner_balance_purchase_return ON partner_balance_entry(purchase_return_id) WHERE purchase_return_id IS NOT NULL;
CREATE UNIQUE INDEX uk_partner_balance_sale_return ON partner_balance_entry(sale_return_id) WHERE sale_return_id IS NOT NULL;
-- +goose Down
SELECT 1;
